// Word packs for WordSpies. 5 curated categories.
const PACKS = {
  easy: {
    name: 'Easy / Family',
    words: [
      'DOG','CAT','SUN','MOON','STAR','TREE','FLOWER','HOUSE','CAR','BUS',
      'TRAIN','PLANE','BOAT','FISH','BIRD','LION','TIGER','BEAR','MONKEY','ELEPHANT',
      'GIRAFFE','ZEBRA','RABBIT','MOUSE','HORSE','COW','PIG','SHEEP','CHICKEN','DUCK',
      'FROG','SNAKE','TURTLE','SHARK','WHALE','DOLPHIN','OCTOPUS','CRAB','BEE','BUTTERFLY',
      'ANT','SPIDER','APPLE','BANANA','ORANGE','GRAPE','LEMON','CHERRY','PEACH','MANGO',
      'PIZZA','BURGER','CAKE','COOKIE','CANDY','ICE CREAM','MILK','JUICE','BREAD','CHEESE',
      'EGG','SOUP','RICE','PASTA','SANDWICH','POPCORN','CHOCOLATE','HONEY','SALT','SUGAR',
      'SCHOOL','TEACHER','BOOK','PENCIL','PAPER','DESK','CHAIR','CLOCK','DOOR','WINDOW',
      'BED','PILLOW','BLANKET','LAMP','MIRROR','BRUSH','SOAP','TOWEL','TOOTHBRUSH','SHAMPOO',
      'BALL','KITE','DOLL','ROBOT','PUZZLE','GAME','TOY','SWING','SLIDE','BIKE',
      'BEACH','OCEAN','RIVER','LAKE','MOUNTAIN','FOREST','DESERT','ISLAND','RAIN','SNOW',
      'CLOUD','WIND','STORM','RAINBOW','FIRE','ICE','ROCK','SAND','GRASS','LEAF',
      'KING','QUEEN','PRINCE','PRINCESS','CASTLE','DRAGON','WIZARD','FAIRY','GIANT','PIRATE',
      'DOCTOR','NURSE','POLICE','FIREFIGHTER','FARMER','CHEF','SINGER','DANCER','CLOWN','ASTRONAUT',
      'HAT','SHOE','SOCK','SHIRT','DRESS','COAT','GLOVE','SCARF','BUTTON','POCKET',
      'HAND','FOOT','EYE','EAR','NOSE','MOUTH','HAIR','TOOTH','FINGER','HEART',
      'MUSIC','DRUM','GUITAR','PIANO','BELL','SONG','MOVIE','CAMERA','PHONE','COMPUTER',
      'BALLOON','PRESENT','PARTY','BIRTHDAY','CIRCUS','ZOO','PARK','FARM','GARDEN','BRIDGE'
    ]
  },
  pop: {
    name: 'Pop Culture',
    words: [
      'BATMAN','SUPERMAN','SPIDER-MAN','HULK','THOR','IRON MAN','AVENGERS','JOKER','GOTHAM','MARVEL',
      'STAR WARS','JEDI','YODA','VADER','LIGHTSABER','WOOKIEE','DROID','HOGWARTS','WAND','MUGGLE',
      'POTTER','VOLDEMORT','QUIDDITCH','GANDALF','HOBBIT','MORDOR','GOLLUM','NARNIA','MATRIX','NEO',
      'TERMINATOR','ROCKY','RAMBO','GODZILLA','KING KONG','JAWS','ALIEN','PREDATOR','TITANIC','AVATAR',
      'SHREK','MINIONS','FROZEN','ELSA','SIMBA','NEMO','WOODY','BUZZ','PIXAR','DISNEY',
      'MARIO','LUIGI','ZELDA','LINK','POKEMON','PIKACHU','SONIC','TETRIS','MINECRAFT','FORTNITE',
      'PACMAN','KIRBY','HALO','DOOM','PORTAL','LARA CROFT','GTA','FIFA','XBOX','NINTENDO',
      'BEATLES','ELVIS','MADONNA','BEYONCE','RIHANNA','DRAKE','EMINEM','ADELE','QUEEN','ABBA',
      'HIP HOP','KARAOKE','GRAMMY','OSCAR','EMMY','NETFLIX','YOUTUBE','TIKTOK','MEME','PODCAST',
      'SHERLOCK','JAMES BOND','ROCKY BALBOA','INDIANA JONES','JURASSIC PARK','BACK TO THE FUTURE','GHOSTBUSTERS','MEN IN BLACK','TRANSFORMERS','X-MEN',
      'SIMPSONS','SOUTH PARK','FAMILY GUY','RICK AND MORTY','SPONGEBOB','SCOOBY DOO','TOM AND JERRY','LOONEY TUNES','PEPPA PIG','DORAEMON',
      'FRIENDS','THE OFFICE','BREAKING BAD','STRANGER THINGS','GAME OF THRONES','SQUID GAME','MONEY HEIST','WEDNESDAY','LOKI','MANDALORIAN',
      'DRACULA','FRANKENSTEIN','ZOMBIE','WEREWOLF','VAMPIRE','MUMMY','GHOST','WITCH','EXORCIST','CHUCKY',
      'SUPERHERO','SIDEKICK','VILLAIN','CAPE','MASK','ORIGIN STORY','SEQUEL','TRILOGY','CAMEO','SPOILER',
      'RED CARPET','PAPARAZZI','SELFIE','INFLUENCER','HASHTAG','VIRAL','EMOJI','STREAMER','GAMER','COSPLAY'
    ]
  },
  animals: {
    name: 'Animals & Nature',
    words: [
      'WOLF','FOX','DEER','MOOSE','BISON','OTTER','BEAVER','BADGER','RACCOON','SKUNK',
      'HEDGEHOG','SQUIRREL','CHIPMUNK','BAT','MOLE','FERRET','WEASEL','LYNX','COUGAR','JAGUAR',
      'LEOPARD','CHEETAH','PANTHER','HYENA','JACKAL','MEERKAT','MONGOOSE','ARMADILLO','SLOTH','ANTEATER',
      'GORILLA','CHIMPANZEE','ORANGUTAN','BABOON','LEMUR','KOALA','WOMBAT','PLATYPUS','OPOSSUM','PANDA',
      'RHINO','HIPPO','BUFFALO','ANTELOPE','GAZELLE','CAMEL','LLAMA','ALPACA','DONKEY','MULE',
      'GOAT','RAM','BULL','OX','YAK','REINDEER','WALRUS','SEAL','SEA LION','MANATEE',
      'ORCA','NARWHAL','STINGRAY','JELLYFISH','STARFISH','SEAHORSE','LOBSTER','SHRIMP','CLAM','OYSTER',
      'SQUID','EEL','PIRANHA','SALMON','TUNA','TROUT','SWORDFISH','CATFISH','GOLDFISH','PUFFERFISH',
      'FLAMINGO','PEACOCK','SWAN','GOOSE','PELICAN','STORK','HERON','CRANE','OSTRICH','EMU',
      'PARROT','TOUCAN','WOODPECKER','HUMMINGBIRD','SPARROW','CROW','RAVEN','MAGPIE','PIGEON','DOVE',
      'FALCON','VULTURE','CONDOR','SEAGULL','PUFFIN','KINGFISHER','NIGHTINGALE','CANARY','CUCKOO','PHEASANT',
      'LIZARD','GECKO','IGUANA','CHAMELEON','COBRA','PYTHON','VIPER','RATTLESNAKE','ALLIGATOR','CROCODILE',
      'TORTOISE','SALAMANDER','NEWT','TOAD','TADPOLE','DRAGONFLY','LADYBUG','BEETLE','MOTH','CATERPILLAR',
      'GRASSHOPPER','CRICKET','MANTIS','FIREFLY','MOSQUITO','WASP','HORNET','TERMITE','SNAIL','EARTHWORM',
      'OAK','PINE','WILLOW','BAMBOO','CACTUS','FERN','MOSS','MUSHROOM','TULIP','SUNFLOWER'
    ]
  },
  food: {
    name: 'Food & Drink',
    words: [
      'TACO','BURRITO','NACHOS','QUESADILLA','SALSA','GUACAMOLE','SUSHI','RAMEN','NOODLES','DUMPLING',
      'SPRING ROLL','FRIED RICE','CURRY','BIRYANI','KEBAB','SAMOSA','NAAN','TANDOORI','FALAFEL','HUMMUS',
      'SHAWARMA','PITA','LASAGNA','SPAGHETTI','RAVIOLI','RISOTTO','GNOCCHI','PESTO','MEATBALL','GARLIC BREAD',
      'CROISSANT','BAGUETTE','PRETZEL','BAGEL','MUFFIN','DONUT','WAFFLE','PANCAKE','CREPE','TOAST',
      'OMELETTE','SCRAMBLED EGG','BACON','SAUSAGE','HAM','STEAK','RIBS','BRISKET','MEATLOAF','GRAVY',
      'HOT DOG','CORN DOG','FRIES','ONION RINGS','COLESLAW','MASHED POTATO','BAKED BEANS','MAC AND CHEESE','GRILLED CHEESE','BLT',
      'CAESAR SALAD','GREEK SALAD','SOUP','CHOWDER','STEW','CHILI','GUMBO','BROTH','PORRIDGE','OATMEAL',
      'CEREAL','GRANOLA','YOGURT','SMOOTHIE','MILKSHAKE','LEMONADE','ICED TEA','COFFEE','ESPRESSO','LATTE',
      'CAPPUCCINO','MOCHA','HOT CHOCOLATE','BUBBLE TEA','SODA','COLA','GINGER ALE','FRUIT PUNCH','COCONUT WATER','APPLE CIDER',
      'BROWNIE','CUPCAKE','CHEESECAKE','TIRAMISU','PUDDING','CUSTARD','GELATO','SORBET','FUDGE','TOFFEE',
      'CARAMEL','MARSHMALLOW','GUMMY BEAR','LOLLIPOP','LICORICE','PEANUT BUTTER','JELLY','NUTELLA','MAPLE SYRUP','WHIPPED CREAM',
      'AVOCADO','BROCCOLI','SPINACH','KALE','CAULIFLOWER','ZUCCHINI','EGGPLANT','PEPPER','ONION','GARLIC',
      'GINGER','MUSHROOM','CORN','PEAS','CELERY','CUCUMBER','RADISH','BEET','TURNIP','PUMPKIN',
      'WATERMELON','CANTALOUPE','PINEAPPLE','PAPAYA','GUAVA','LYCHEE','POMEGRANATE','FIG','DATE','APRICOT',
      'BLUEBERRY','RASPBERRY','BLACKBERRY','CRANBERRY','COCONUT','ALMOND','CASHEW','PISTACHIO','WALNUT','PECAN'
    ]
  },
  places: {
    name: 'Travel & Places',
    words: [
      'PARIS','ROME','VENICE','MADRID','BARCELONA','LISBON','AMSTERDAM','VIENNA','PRAGUE','ATHENS',
      'DUBLIN','EDINBURGH','STOCKHOLM','OSLO','HELSINKI','COPENHAGEN','BRUSSELS','ZURICH','GENEVA','MUNICH',
      'ISTANBUL','CAIRO','MARRAKECH','CAPE TOWN','NAIROBI','LAGOS','CASABLANCA','TUNIS','ZANZIBAR','SAHARA',
      'DUBAI','ABU DHABI','DOHA','RIYADH','JERUSALEM','PETRA','BAGHDAD','TEHRAN','KABUL','KARACHI',
      'LAHORE','ISLAMABAD','DELHI','MUMBAI','JAIPUR','GOA','KATHMANDU','COLOMBO','DHAKA','TAJ MAHAL',
      'BANGKOK','SINGAPORE','KUALA LUMPUR','JAKARTA','BALI','MANILA','HANOI','SAIGON','PHUKET','SEOUL',
      'KYOTO','OSAKA','SHANGHAI','HONG KONG','TAIPEI','MACAU','MONGOLIA','TIBET','EVEREST','GREAT WALL',
      'SYDNEY','MELBOURNE','AUCKLAND','FIJI','TAHITI','HAWAII','BORA BORA','MALDIVES','SEYCHELLES','MADAGASCAR',
      'TORONTO','VANCOUVER','MONTREAL','ALASKA','SEATTLE','PORTLAND','SAN FRANCISCO','LOS ANGELES','LAS VEGAS','DENVER',
      'CHICAGO','BOSTON','MIAMI','ORLANDO','NASHVILLE','NEW ORLEANS','TEXAS','ARIZONA','GRAND CANYON','YELLOWSTONE',
      'MEXICO CITY','CANCUN','HAVANA','JAMAICA','BAHAMAS','PANAMA','BOGOTA','LIMA','CUSCO','MACHU PICCHU',
      'RIO','SAO PAULO','BUENOS AIRES','PATAGONIA','SANTIAGO','GALAPAGOS','AMAZON','ANDES','CARIBBEAN','BERMUDA',
      'AIRPORT','PASSPORT','SUITCASE','BACKPACK','HOSTEL','RESORT','CRUISE','FERRY','SUBWAY','TAXI',
      'LIGHTHOUSE','HARBOR','CASTLE','PALACE','CATHEDRAL','MOSQUE','TEMPLE','MUSEUM','FOUNTAIN','MONUMENT',
      'VOLCANO','GLACIER','WATERFALL','CANYON','OASIS','LAGOON','REEF','CLIFF','VALLEY','MEADOW'
    ]
  }
};

module.exports = { PACKS };
