// Word packs for WordSpies. 5 curated categories.
const PACKS = {
  easy: {
    name: 'Easy / Family',
    words: [
      'DOG','CAT','SUN','MOON','STAR','TREE','FLOWER','HOUSE','CAR','BUS',
      'TRAIN','PLANE','BOAT','FISH','BIRD','LION','TIGER','BEAR','MONKEY','ELEPHANT',
      'GIRAFFE','ZEBRA','RABBIT','MOUSE','HORSE','COW','PIG','SHEEP','CHICKEN','DUCK',
      'FROG','SNAKE','TURTLE','SHARK','WHALE','DOLPHIN','OCTOPUS','CRAB','BEE','BUTTERFLY',
      'ANT','SPIDER','APPLE','BANANA','ORANGE','GRAPE','LEMON','CHERRY','PEACH','MANGO',
      'PIZZA','BURGER','CAKE','COOKIE','CANDY','ICE CREAM','MILK','JUICE','BREAD','CHEESE',
      'EGG','SOUP','RICE','PASTA','SANDWICH','POPCORN','CHOCOLATE','HONEY','SALT','SUGAR',
      'SCHOOL','TEACHER','BOOK','PENCIL','PAPER','DESK','CHAIR','CLOCK','DOOR','WINDOW',
      'BED','PILLOW','BLANKET','LAMP','MIRROR','BRUSH','SOAP','TOWEL','TOOTHBRUSH','SHAMPOO',
      'BALL','KITE','DOLL','ROBOT','PUZZLE','GAME','TOY','SWING','SLIDE','BIKE',
      'BEACH','OCEAN','RIVER','LAKE','MOUNTAIN','FOREST','DESERT','ISLAND','RAIN','SNOW',
      'CLOUD','WIND','STORM','RAINBOW','FIRE','ICE','ROCK','SAND','GRASS','LEAF',
      'KING','QUEEN','PRINCE','PRINCESS','CASTLE','DRAGON','WIZARD','FAIRY','GIANT','PIRATE',
      'DOCTOR','NURSE','POLICE','FIREFIGHTER','FARMER','CHEF','SINGER','DANCER','CLOWN','ASTRONAUT',
      'HAT','SHOE','SOCK','SHIRT','DRESS','COAT','GLOVE','SCARF','BUTTON','POCKET',
      'HAND','FOOT','EYE','EAR','NOSE','MOUTH','HAIR','TOOTH','FINGER','HEART',
      'MUSIC','DRUM','GUITAR','PIANO','BELL','SONG','MOVIE','CAMERA','PHONE','COMPUTER',
      'BALLOON','PRESENT','PARTY','BIRTHDAY','CIRCUS','ZOO','PARK','FARM','GARDEN','BRIDGE'
    ]
  },
  pop: {
    name: 'Pop Culture',
    words: [
      'BATMAN','SUPERMAN','SPIDER-MAN','HULK','THOR','IRON MAN','AVENGERS','JOKER','GOTHAM','MARVEL',
      'STAR WARS','JEDI','YODA','VADER','LIGHTSABER','WOOKIEE','DROID','HOGWARTS','WAND','MUGGLE',
      'POTTER','VOLDEMORT','QUIDDITCH','GANDALF','HOBBIT','MORDOR','GOLLUM','NARNIA','MATRIX','NEO',
      'TERMINATOR','ROCKY','RAMBO','GODZILLA','KING KONG','JAWS','ALIEN','PREDATOR','TITANIC','AVATAR',
      'SHREK','MINIONS','FROZEN','ELSA','SIMBA','NEMO','WOODY','BUZZ','PIXAR','DISNEY',
      'MARIO','LUIGI','ZELDA','LINK','POKEMON','PIKACHU','SONIC','TETRIS','MINECRAFT','FORTNITE',
      'PACMAN','KIRBY','HALO','DOOM','PORTAL','LARA CROFT','GTA','FIFA','XBOX','NINTENDO',
      'BEATLES','ELVIS','MADONNA','BEYONCE','RIHANNA','DRAKE','EMINEM','ADELE','QUEEN','ABBA',
      'HIP HOP','KARAOKE','GRAMMY','OSCAR','EMMY','NETFLIX','YOUTUBE','TIKTOK','MEME','PODCAST',
      'SHERLOCK','JAMES BOND','ROCKY BALBOA','INDIANA JONES','JURASSIC PARK','BACK TO THE FUTURE','GHOSTBUSTERS','MEN IN BLACK','TRANSFORMERS','X-MEN',
      'SIMPSONS','SOUTH PARK','FAMILY GUY','RICK AND MORTY','SPONGEBOB','SCOOBY DOO','TOM AND JERRY','LOONEY TUNES','PEPPA PIG','DORAEMON',
      'FRIENDS','THE OFFICE','BREAKING BAD','STRANGER THINGS','GAME OF THRONES','SQUID GAME','MONEY HEIST','WEDNESDAY','LOKI','MANDALORIAN',
      'DRACULA','FRANKENSTEIN','ZOMBIE','WEREWOLF','VAMPIRE','MUMMY','GHOST','WITCH','EXORCIST','CHUCKY',
      'SUPERHERO','SIDEKICK','VILLAIN','CAPE','MASK','ORIGIN STORY','SEQUEL','TRILOGY','CAMEO','SPOILER',
      'RED CARPET','PAPARAZZI','SELFIE','INFLUENCER','HASHTAG','VIRAL','EMOJI','STREAMER','GAMER','COSPLAY'
    ]
  },
  animals: {
    name: 'Animals & Nature',
    words: [
      'WOLF','FOX','DEER','MOOSE','BISON','OTTER','BEAVER','BADGER','RACCOON','SKUNK',
      'HEDGEHOG','SQUIRREL','CHIPMUNK','BAT','MOLE','FERRET','WEASEL','LYNX','COUGAR','JAGUAR',
      'LEOPARD','CHEETAH','PANTHER','HYENA','JACKAL','MEERKAT','MONGOOSE','ARMADILLO','SLOTH','ANTEATER',
      'GORILLA','CHIMPANZEE','ORANGUTAN','BABOON','LEMUR','KOALA','WOMBAT','PLATYPUS','OPOSSUM','PANDA',
      'RHINO','HIPPO','BUFFALO','ANTELOPE','GAZELLE','CAMEL','LLAMA','ALPACA','DONKEY','MULE',
      'GOAT','RAM','BULL','OX','YAK','REINDEER','WALRUS','SEAL','SEA LION','MANATEE',
      'ORCA','NARWHAL','STINGRAY','JELLYFISH','STARFISH','SEAHORSE','LOBSTER','SHRIMP','CLAM','OYSTER',
      'SQUID','EEL','PIRANHA','SALMON','TUNA','TROUT','SWORDFISH','CATFISH','GOLDFISH','PUFFERFISH',
      'FLAMINGO','PEACOCK','SWAN','GOOSE','PELICAN','STORK','HERON','CRANE','OSTRICH','EMU',
      'PARROT','TOUCAN','WOODPECKER','HUMMINGBIRD','SPARROW','CROW','RAVEN','MAGPIE','PIGEON','DOVE',
      'FALCON','VULTURE','CONDOR','SEAGULL','PUFFIN','KINGFISHER','NIGHTINGALE','CANARY','CUCKOO','PHEASANT',
      'LIZARD','GECKO','IGUANA','CHAMELEON','COBRA','PYTHON','VIPER','RATTLESNAKE','ALLIGATOR','CROCODILE',
      'TORTOISE','SALAMANDER','NEWT','TOAD','TADPOLE','DRAGONFLY','LADYBUG','BEETLE','MOTH','CATERPILLAR',
      'GRASSHOPPER','CRICKET','MANTIS','FIREFLY','MOSQUITO','WASP','HORNET','TERMITE','SNAIL','EARTHWORM',
      'OAK','PINE','WILLOW','BAMBOO','CACTUS','FERN','MOSS','MUSHROOM','TULIP','SUNFLOWER'
    ]
  },
  food: {
    name: 'Food & Drink',
    words: [
      'TACO','BURRITO','NACHOS','QUESADILLA','SALSA','GUACAMOLE','SUSHI','RAMEN','NOODLES','DUMPLING',
      'SPRING ROLL','FRIED RICE','CURRY','BIRYANI','KEBAB','SAMOSA','NAAN','TANDOORI','FALAFEL','HUMMUS',
      'SHAWARMA','PITA','LASAGNA','SPAGHETTI','RAVIOLI','RISOTTO','GNOCCHI','PESTO','MEATBALL','GARLIC BREAD',
      'CROISSANT','BAGUETTE','PRETZEL','BAGEL','MUFFIN','DONUT','WAFFLE','PANCAKE','CREPE','TOAST',
      'OMELETTE','SCRAMBLED EGG','BACON','SAUSAGE','HAM','STEAK','RIBS','BRISKET','MEATLOAF','GRAVY',
      'HOT DOG','CORN DOG','FRIES','ONION RINGS','COLESLAW','MASHED POTATO','BAKED BEANS','MAC AND CHEESE','GRILLED CHEESE','BLT',
      'CAESAR SALAD','GREEK SALAD','SOUP','CHOWDER','STEW','CHILI','GUMBO','BROTH','PORRIDGE','OATMEAL',
      'CEREAL','GRANOLA','YOGURT','SMOOTHIE','MILKSHAKE','LEMONADE','ICED TEA','COFFEE','ESPRESSO','LATTE',
      'CAPPUCCINO','MOCHA','HOT CHOCOLATE','BUBBLE TEA','SODA','COLA','GINGER ALE','FRUIT PUNCH','COCONUT WATER','APPLE CIDER',
      'BROWNIE','CUPCAKE','CHEESECAKE','TIRAMISU','PUDDING','CUSTARD','GELATO','SORBET','FUDGE','TOFFEE',
      'CARAMEL','MARSHMALLOW','GUMMY BEAR','LOLLIPOP','LICORICE','PEANUT BUTTER','JELLY','NUTELLA','MAPLE SYRUP','WHIPPED CREAM',
      'AVOCADO','BROCCOLI','SPINACH','KALE','CAULIFLOWER','ZUCCHINI','EGGPLANT','PEPPER','ONION','GARLIC',
      'GINGER','MUSHROOM','CORN','PEAS','CELERY','CUCUMBER','RADISH','BEET','TURNIP','PUMPKIN',
      'WATERMELON','CANTALOUPE','PINEAPPLE','PAPAYA','GUAVA','LYCHEE','POMEGRANATE','FIG','DATE','APRICOT',
      'BLUEBERRY','RASPBERRY','BLACKBERRY','CRANBERRY','COCONUT','ALMOND','CASHEW','PISTACHIO','WALNUT','PECAN'
    ]
  },
  places: {
    name: 'Travel & Places',
    words: [
      'PARIS','ROME','VENICE','MADRID','BARCELONA','LISBON','AMSTERDAM','VIENNA','PRAGUE','ATHENS',
      'DUBLIN','EDINBURGH','STOCKHOLM','OSLO','HELSINKI','COPENHAGEN','BRUSSELS','ZURICH','GENEVA','MUNICH',
      'ISTANBUL','CAIRO','MARRAKECH','CAPE TOWN','NAIROBI','LAGOS','CASABLANCA','TUNIS','ZANZIBAR','SAHARA',
      'DUBAI','ABU DHABI','DOHA','RIYADH','JERUSALEM','PETRA','BAGHDAD','TEHRAN','KABUL','KARACHI',
      'LAHORE','ISLAMABAD','DELHI','MUMBAI','JAIPUR','GOA','KATHMANDU','COLOMBO','DHAKA','TAJ MAHAL',
      'BANGKOK','SINGAPORE','KUALA LUMPUR','JAKARTA','BALI','MANILA','HANOI','SAIGON','PHUKET','SEOUL',
      'KYOTO','OSAKA','SHANGHAI','HONG KONG','TAIPEI','MACAU','MONGOLIA','TIBET','EVEREST','GREAT WALL',
      'SYDNEY','MELBOURNE','AUCKLAND','FIJI','TAHITI','HAWAII','BORA BORA','MALDIVES','SEYCHELLES','MADAGASCAR',
      'TORONTO','VANCOUVER','MONTREAL','ALASKA','SEATTLE','PORTLAND','SAN FRANCISCO','LOS ANGELES','LAS VEGAS','DENVER',
      'CHICAGO','BOSTON','MIAMI','ORLANDO','NASHVILLE','NEW ORLEANS','TEXAS','ARIZONA','GRAND CANYON','YELLOWSTONE',
      'MEXICO CITY','CANCUN','HAVANA','JAMAICA','BAHAMAS','PANAMA','BOGOTA','LIMA','CUSCO','MACHU PICCHU',
      'RIO','SAO PAULO','BUENOS AIRES','PATAGONIA','SANTIAGO','GALAPAGOS','AMAZON','ANDES','CARIBBEAN','BERMUDA',
      'AIRPORT','PASSPORT','SUITCASE','BACKPACK','HOSTEL','RESORT','CRUISE','FERRY','SUBWAY','TAXI',
      'LIGHTHOUSE','HARBOR','CASTLE','PALACE','CATHEDRAL','MOSQUE','TEMPLE','MUSEUM','FOUNTAIN','MONUMENT',
      'VOLCANO','GLACIER','WATERFALL','CANYON','OASIS','LAGOON','REEF','CLIFF','VALLEY','MEADOW'
    ]
  },
  cities: {
    name: 'Cities',
    words: [
      'PARIS','LONDON','TOKYO','ROME','CAIRO','BERLIN','MADRID','DUBAI','SYDNEY','MUMBAI',
      'MOSCOW','ATHENS','VENICE','LISBON','VIENNA','PRAGUE','DUBLIN','OSLO','SEOUL','DELHI',
      'BOSTON','DALLAS','DENVER','MIAMI','CHICAGO','TORONTO','HAVANA','LIMA','QUITO','BOGOTA',
      'NAIROBI','LAGOS','ACCRA','TUNIS','RABAT','DAKAR','MANILA','HANOI','BANGKOK','JAKARTA',
      'KARACHI','LAHORE','KABUL','TEHRAN','BAGHDAD','DOHA','MUSCAT','AMMAN','BEIRUT','ANKARA',
      'MUNICH','ZURICH','GENEVA','NAPLES','TURIN','SEVILLE','PORTO','BILBAO','CANNES','NICE',
      'HELSINKI','BERGEN','GLASGOW','LEEDS','BRISTOL','CARDIFF','BELFAST','DERBY','HULL','YORK'
    ]
  },
  countries: {
    name: 'Countries',
    words: [
      'FRANCE','JAPAN','BRAZIL','EGYPT','CANADA','INDIA','SPAIN','ITALY','CHINA','KENYA',
      'MEXICO','PERU','CHILE','CUBA','GREECE','TURKEY','NORWAY','SWEDEN','POLAND','IRELAND',
      'PORTUGAL','MOROCCO','NIGERIA','GHANA','ANGOLA','ZAMBIA','UGANDA','JORDAN','IRAQ','IRAN',
      'NEPAL','TIBET','KOREA','VIETNAM','THAILAND','MALAYSIA','INDONESIA','PAKISTAN','AFGHANISTAN','QATAR',
      'GERMANY','AUSTRIA','BELGIUM','DENMARK','FINLAND','ICELAND','CROATIA','SERBIA','HUNGARY','ROMANIA',
      'ARGENTINA','COLOMBIA','ECUADOR','BOLIVIA','URUGUAY','PANAMA','JAMAICA','HAITI','FIJI','TONGA'
    ]
  },
  movies: {
    name: 'Movies & TV',
    words: [
      'AVATAR','TITANIC','JAWS','FROZEN','MATRIX','ALIEN','ROCKY','BATMAN','JOKER','SHREK',
      'GLADIATOR','INCEPTION','GHOSTBUSTERS','TWILIGHT','DRACULA','GODZILLA','KINGKONG','TERMINATOR','PREDATOR','RAMBO',
      'STAR','WARS','JEDI','WIZARD','HOBBIT','NARNIA','POTTER','PIRATES','MUMMY','TITANS',
      'ACTOR','DIRECTOR','SCRIPT','SCENE','STUDIO','TRAILER','SEQUEL','VILLAIN','HERO','SIDEKICK',
      'OSCAR','SCREEN','CAMERA','ACTION','COMEDY','HORROR','ROMANCE','THRILLER','CARTOON','SITCOM',
      'NETFLIX','PREMIERE','POPCORN','CINEMA','REMOTE','SEASON','EPISODE','FINALE','SPINOFF','REBOOT'
    ]
  },
  sports: {
    name: 'Sports & Football',
    words: [
      'GOAL','PENALTY','STRIKER','KEEPER','PITCH','REFEREE','CORNER','DERBY','LEAGUE','WHISTLE',
      'DRIBBLE','TACKLE','OFFSIDE','HEADER','VOLLEY','KICKOFF','STADIUM','JERSEY','CAPTAIN','MIDFIELD',
      'TENNIS','BOXING','GOLF','RUGBY','CRICKET','HOCKEY','SKIING','ROWING','CYCLING','SWIMMING',
      'RACKET','GLOVE','HELMET','WHISTLE','TROPHY','MEDAL','PODIUM','SPRINT','MARATHON','RELAY',
      'BASKET','DUNK','SERVE','SMASH','RALLY','INNINGS','WICKET','BOWLER','BATTER','UMPIRE',
      'COACH','SUBSTITUTE','FORMATION','FIXTURE','SEASON','CHAMPION','RUNNER','HURDLE','JAVELIN','DISCUS'
    ]
  },
  tech: {
    name: 'Technology & Gadgets',
    words: [
      'PHONE','LAPTOP','TABLET','ROBOT','DRONE','CAMERA','HEADPHONES','SPEAKER','KEYBOARD','MOUSE',
      'MONITOR','PRINTER','ROUTER','WIFI','BLUETOOTH','CHARGER','BATTERY','USB','INTERNET','WEBSITE',
      'APP','SOFTWARE','HARDWARE','ALGORITHM','DATABASE','SERVER','CLOUD','EMAIL','PASSWORD','VIRUS',
      'HACKER','CODE','PROGRAMMER','WEBCAM','MICROPHONE','JOYSTICK','CONSOLE','CHIP','PROCESSOR','MEMORY',
      'SCREEN','TOUCHSCREEN','SMARTWATCH','GADGET','SATELLITE','GPS','SENSOR','CIRCUIT','STARTUP','WEBPAGE',
      'DASHBOARD','INTERFACE','BANDWIDTH','ZOOM','PODCAST','STREAMING','DOWNLOAD','UPLOAD','FIREWALL','ANTIVIRUS',
      'BROWSER','FLASHDRIVE','EARBUDS','TOUCHPAD','SPREADSHEET','ATTACHMENT','UPDATE','BACKUP','ENCRYPTION','BITCOIN'
    ]
  },
  music: {
    name: 'Music & Bands',
    words: [
      'GUITAR','DRUMS','PIANO','VIOLIN','TRUMPET','SAXOPHONE','FLUTE','HARP','CELLO','BASS',
      'MICROPHONE','AMPLIFIER','SPEAKER','HEADPHONES','PLAYLIST','ALBUM','SINGLE','CONCERT','FESTIVAL','TOUR',
      'LYRICS','MELODY','RHYTHM','BEAT','CHORUS','VERSE','BAND','SOLO','DUET','ORCHESTRA',
      'CHOIR','ROCK','POP','JAZZ','BLUES','RAPPER','COUNTRY','CLASSICAL','REGGAE','FOLK',
      'METAL','PUNK','DISCO','TECHNO','OPERA','SYMPHONY','ANTHEM','BALLAD','REMIX','COVER',
      'GRAMMY','BILLBOARD','VINYL','RADIO','STAGE','SPOTLIGHT','ENCORE','BACKSTAGE','SETLIST','KARAOKE'
    ]
  },
  jobs: {
    name: 'Jobs & Occupations',
    words: [
      'DOCTOR','NURSE','TEACHER','ENGINEER','LAWYER','OFFICER','FIREFIGHTER','PILOT','CHEF','FARMER',
      'DENTIST','ARCHITECT','ACCOUNTANT','ELECTRICIAN','PLUMBER','MECHANIC','CARPENTER','PAINTER','CAMERAMAN','JOURNALIST',
      'SCIENTIST','ASTRONAUT','SOLDIER','SAILOR','BAKER','BUTCHER','BARBER','HAIRDRESSER','TAILOR','JUDGE',
      'ACTOR','MUSICIAN','ARTIST','WRITER','LIBRARIAN','CASHIER','WAITER','BARTENDER','GUARD','VET',
      'SURGEON','PHARMACIST','THERAPIST','COUNSELOR','PRINCIPAL','PROFESSOR','RESEARCHER','ANALYST','MANAGER','CEO',
      'SALESPERSON','ASSISTANT','SECRETARY','DRIVER','COURIER','POSTMAN','GARDENER','CLEANER','LIFEGUARD','COACH'
    ]
  },
  weather: {
    name: 'Weather & Seasons',
    words: [
      'SUN','RAIN','SNOW','WIND','CLOUD','STORM','THUNDER','LIGHTNING','FOG','MIST',
      'HAIL','FROST','ICE','HEATWAVE','DROUGHT','FLOOD','HURRICANE','TORNADO','BLIZZARD','MONSOON',
      'RAINBOW','TEMPERATURE','FORECAST','UMBRELLA','RAINCOAT','SUNSHINE','BREEZE','GALE','HUMIDITY','DEW',
      'SPRING','SUMMER','AUTUMN','WINTER','SUNRISE','SUNSET','SEASON','CLIMATE','BAROMETER','THERMOMETER',
      'SNOWFLAKE','SNOWMAN','ICICLE','PUDDLE','DRIZZLE','SHOWER','OVERCAST','SUNNY','CLOUDY','WINDY'
    ]
  },
  vehicles: {
    name: 'Vehicles & Transportation',
    words: [
      'CAR','TRUCK','BUS','TRAIN','PLANE','HELICOPTER','BOAT','SHIP','SUBMARINE','BICYCLE',
      'MOTORCYCLE','SCOOTER','SKATEBOARD','TRAM','SUBWAY','TAXI','AMBULANCE','ENGINE','CRUISER','TRACTOR',
      'VAN','JEEP','LIMOUSINE','CONVERTIBLE','PICKUP','CARAVAN','TRAILER','FORKLIFT','BULLDOZER','CRANE',
      'ROCKET','SPACESHIP','AIRSHIP','GLIDER','JET','YACHT','CANOE','KAYAK','FERRY','LINER',
      'SLEIGH','CARRIAGE','WHEELBARROW','SEGWAY','KART','RICKSHAW','GONDOLA','MONORAIL','ROAD','HIGHWAY',
      'RUNWAY','STATION','GARAGE','PARKING','SIGNAL'
    ]
  },
  space: {
    name: 'Space & Science',
    words: [
      'PLANET','MOON','GALAXY','COMET','METEOR','ASTEROID','ORBIT','ROCKET','SATELLITE','ASTRONAUT',
      'TELESCOPE','UNIVERSE','NEBULA','SUPERNOVA','ECLIPSE','GRAVITY','ATMOSPHERE','OXYGEN','HYDROGEN','ATOM',
      'MOLECULE','ELEMENT','CHEMISTRY','PHYSICS','BIOLOGY','GENETICS','EVOLUTION','DINOSAUR','FOSSIL','VOLCANO',
      'EARTHQUAKE','TSUNAMI','MAGNET','ELECTRICITY','ENERGY','LASER','MICROSCOPE','EXPERIMENT','LABORATORY','VACCINE',
      'BACTERIA','VIRUS','NEURON','BRAIN','SKELETON','MUSCLE','CRYSTAL','MINERAL','CHEMICAL','REACTION',
      'FORMULA','EQUATION','THEORY','HYPOTHESIS','RESEARCH','DISCOVERY','INVENTION','ROBOTICS','SPACESHIP','ASTRONOMY'
    ]
  },
  emotions: {
    name: 'Emotions & Feelings',
    words: [
      'HAPPY','SAD','ANGRY','EXCITED','NERVOUS','SCARED','PROUD','JEALOUS','CONFUSED','SURPRISED',
      'CALM','ANXIOUS','GRATEFUL','HOPEFUL','LONELY','EMBARRASSED','CURIOUS','BORED','TIRED','RELAXED',
      'STRESSED','CONFIDENT','SHY','BRAVE','GUILTY','CONTENT','JOYFUL','MISERABLE','FRUSTRATED','OPTIMISTIC',
      'GRUMPY','CHEERFUL','NOSTALGIC','OVERWHELMED','INSECURE','SATISFIED','UPSET','EAGER','PEACEFUL','THANKFUL',
      'AMUSED','ASHAMED','DELIGHTED','ANNOYED','TERRIFIED','RELIEVED','PASSIONATE','HEARTBROKEN','ECSTATIC','MOODY'
    ]
  },
  fashion: {
    name: 'Fashion & Clothing',
    words: [
      'SHIRT','PANTS','DRESS','SKIRT','JACKET','SWEATER','HOODIE','JEANS','SHORTS','BLAZER',
      'SUIT','TUXEDO','GOWN','SCARF','GLOVES','BOOTS','SNEAKERS','SANDALS','HEELS','SLIPPERS',
      'HAT','CAP','BEANIE','BELT','TIE','BOWTIE','NECKLACE','BRACELET','EARRINGS','RING',
      'WATCH','SUNGLASSES','HANDBAG','BACKPACK','WALLET','UMBRELLA','RAINCOAT','CARDIGAN','VEST','ROBE',
      'PAJAMAS','SWIMSUIT','LEGGINGS','TIGHTS','MITTENS','EARMUFFS','APRON','UNIFORM','COSTUME','TURBAN'
    ]
  }
};

// key -> display name, for the lobby category picker
const CATALOG = Object.entries(PACKS).map(([key, p]) => ({ key, name: p.name }));

module.exports = { PACKS, CATALOG };
